/**
 * 算得清统一账本 Store。
 * 账本蓝图规范：交易以分存储；收入、退款、销售成本和经营费用分开聚合；页面不再使用固定营收或合成趋势。
 */
import { useEffect, useMemo, useState } from "react";
import { buildMetrics, entriesForPeriod, fromFen, periodOf, periodSeries, previousPeriod, toFen, type BudgetBasis, type CashDirection, type LedgerEntry, type LedgerEventType, type LedgerRole } from "./ledger-metrics";
import { buildOrderEntries, buildRefundEntries, getOrderPricingAlert, lineCogsFen, lineRevenueFen, orderCogsFen, orderGrossFen, refundableQuantity, type ChannelPricingSnapshot, type Order, type OrderChannel, type OrderLine, type RefundCase, type RefundReason, type ReturnRecoveryStatus, type Sku } from "./order-ledger";

export type IndustryId = "canteen" | "retail" | "ecommerce" | "beauty" | "stall";
export type RecordType = "expense" | "income" | "refund";
export type RecordStatus = "accounted" | "pending" | "abnormal";
export type Category = { id: string; workspaceId: string; industryId: IndustryId; key: string; label: string; color: string; hint: string; ledgerRole: "cogs" | "opex" | "other_income"; archived?: boolean };
export type CostRecord = Omit<LedgerEntry, "status"> & { date: string; type: RecordType; amount: number; status: RecordStatus };
export type BomItem = { id: string; name: string; spec: string; quantity: string; amount: number };
export type CostCard = { id: string; workspaceId: string; industryId: IndustryId; name: string; kind: string; unit: string; salePrice: number; labor: number; overhead: number; items: BomItem[]; history: number[]; status: "healthy" | "attention" | "risk" };
export type Supplier = { id: string; workspaceId: string; industryIds: (IndustryId | "shared")[]; name: string; contact: string; categoryKey: string; spend: number; orders: number; trend: "up" | "down" };
export type Report = { id: string; workspaceId: string; industryId: IndustryId; month: string; revenue: number; cost: number; margin: number; grossMarginRate: number; operatingMarginRate: number; status: "draft" | "closed"; snapshot: { key: string; label: string; amount: number; pct: number; delta: number }[] };
export type IndustryTemplate = { id: IndustryId; label: string; descriptor: string; storeName: string; budget: number; entityLabel: string; formulaLabel: string; unitLabel: string; risk: string; riskNote: string; categories: Omit<Category, "id" | "workspaceId" | "industryId">[]; hiddenCost: { key: string; label: string; rate: number; basisKeys: string[]; tip: string }[] };
export type SalesTargetArchive = { id: string; workspaceId: string; industryId: IndustryId; period: string; targetFen: number; savedAt: string };
export type HealthSettings = { targetOperatingMarginPct: number; refundTolerancePct: number };

type Budget = { amountFen: number; basis: BudgetBasis };
type BookState = { schemaVersion: 3; workspace: { id: string; activeIndustryId: IndustryId; budgets: Record<IndustryId, Budget>; /** 月销售目标，以分存储；0 表示该行业尚未设置目标。 */ salesTargets: Record<IndustryId, number>; healthSettings: Record<IndustryId, HealthSettings>; channelPricing: Record<OrderChannel, ChannelPricingSnapshot>; switchedAt: string; dataMode: "demo" | "live" | "legacy_review" }; categories: Category[]; entries: LedgerEntry[]; cards: CostCard[]; skus: Sku[]; orders: Order[]; refunds: RefundCase[]; suppliers: Supplier[]; salesTargetArchives: SalesTargetArchive[]; closedReports: Report[]; switchLog: { id: string; from: IndustryId; to: IndustryId; at: string; strategy: "future_only" }[] };

const WORKSPACE_ID = "workspace-main";
const STORAGE_KEY = "sqd-mobile-book-v3";
const V2_STORAGE_KEY = "sqd-mobile-book-v2";
const LEGACY_STORAGE_KEY = "sqd-mobile-book-v1";
const now = () => new Date().toISOString();
const uid = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const periods = ["2026-02", "2026-03", "2026-04", "2026-05", "2026-06", "2026-07"];
const defaultChannelPricing = (): Record<OrderChannel, ChannelPricingSnapshot> => ({ platform: { commissionRatePct: 0, fulfillmentCost: 0, targetContributionMarginPct: 40, roundingStep: 1 }, live: { commissionRatePct: 0, fulfillmentCost: 0, targetContributionMarginPct: 40, roundingStep: 1 }, store: { commissionRatePct: 0, fulfillmentCost: 0, targetContributionMarginPct: 40, roundingStep: 1 }, private: { commissionRatePct: 0, fulfillmentCost: 0, targetContributionMarginPct: 40, roundingStep: 1 }, other: { commissionRatePct: 0, fulfillmentCost: 0, targetContributionMarginPct: 40, roundingStep: 1 } });
const defaultSalesTargets = (): Record<IndustryId, number> => Object.fromEntries((Object.keys(industryTemplates) as IndustryId[]).map((id) => [id, 0])) as Record<IndustryId, number>;
const defaultHealthSettings = (): Record<IndustryId, HealthSettings> => Object.fromEntries((Object.keys(industryTemplates) as IndustryId[]).map((id) => [id, { targetOperatingMarginPct: 0, refundTolerancePct: 0 }])) as Record<IndustryId, HealthSettings>;

const roleFor = (key: string): Category["ledgerRole"] => ["food_purchase", "goods_purchase", "fulfillment", "warehouse_packaging", "materials", "technician_labor", "purchase", "logistics_storage", "delivery"].includes(key) ? "cogs" : "opex";
const categories = (items: { key: string; label: string; color: string; hint: string }[]) => items.map((item) => ({ ...item, ledgerRole: roleFor(item.key) }));

export const industryTemplates: Record<IndustryId, IndustryTemplate> = {
  canteen: { id: "canteen", label: "餐饮", descriptor: "餐厅 / 小吃 / 饮品店", storeName: "川味小馆", budget: 160000, entityLabel: "菜品", formulaLabel: "配方", unitLabel: "份", risk: "食材采购超预算，需要核对损耗", riskNote: "先盘点报损和高耗用菜品，再核对本周采购批次差价。", categories: categories([{ key: "food_purchase", label: "食材采购", color: "#1677FF", hint: "食材 / 粮油 / 调料" }, { key: "labor", label: "人力工资", color: "#12B76A", hint: "后厨 / 前厅 / 提成" }, { key: "rent_utilities", label: "房租水电", color: "#F79009", hint: "租金 / 水电 / 物业" }, { key: "marketing", label: "营销推广", color: "#7F56D9", hint: "团购 / 本地生活" }, { key: "logistics_storage", label: "物流仓储", color: "#0B1836", hint: "冷链 / 配送 / 仓储" }, { key: "depreciation", label: "设备折旧", color: "#F04438", hint: "厨房设备" }, { key: "other", label: "其他", color: "#A3AEC2", hint: "其他支出" }]), hiddenCost: [{ key: "food_loss", label: "食材损耗", rate: .07, basisKeys: ["food_purchase"], tip: "登记报损并按日盘点，替换基准估算。" }, { key: "utility_loss", label: "水电隐性浪费", rate: .1, basisKeys: ["rent_utilities"], tip: "识别冷库和待机能耗。" }, { key: "expiry", label: "库存过期", rate: .03, basisKeys: ["food_purchase"], tip: "按先进先出补货。" }] },
  retail: { id: "retail", label: "零售", descriptor: "服饰 / 百货 / 便利店", storeName: "橙子优选店", budget: 150000, entityLabel: "商品", formulaLabel: "成本构成", unitLabel: "件", risk: "低周转库存正在占用资金", riskNote: "筛选近 60 天未动销商品，优先安排折扣和搭售。", categories: categories([{ key: "goods_purchase", label: "商品采购", color: "#1677FF", hint: "进货 / 补货" }, { key: "labor", label: "人力工资", color: "#12B76A", hint: "店员 / 提成" }, { key: "rent_utilities", label: "房租水电", color: "#F79009", hint: "租金 / 物业" }, { key: "marketing", label: "营销推广", color: "#7F56D9", hint: "促销 / 折扣" }, { key: "delivery", label: "物流配送", color: "#0B1836", hint: "配送 / 调货" }, { key: "shrinkage", label: "损耗报损", color: "#F04438", hint: "破损 / 丢失" }, { key: "other", label: "其他", color: "#A3AEC2", hint: "其他支出" }]), hiddenCost: [{ key: "shrinkage", label: "门店损耗", rate: .016, basisKeys: ["goods_purchase"], tip: "定期盘点并核对破损与上架流程。" }, { key: "carrying", label: "库存持有", rate: .021, basisKeys: ["goods_purchase"], tip: "压缩高值低周转库存。" }, { key: "obsolete", label: "滞销过时", rate: .125, basisKeys: ["goods_purchase"], tip: "在过季前提前促销清库。" }] },
  ecommerce: { id: "ecommerce", label: "电商", descriptor: "平台店 / 直播店 / 独立站", storeName: "蓝鲸电商店", budget: 150000, entityLabel: "商品", formulaLabel: "成本构成", unitLabel: "件", risk: "退款与广告投放需要优先复核", riskNote: "把退款后的实收与投放消耗放在同一张账，先停掉低转化计划。", categories: categories([{ key: "goods_purchase", label: "商品采购", color: "#1677FF", hint: "货品 / 补货" }, { key: "platform_fee", label: "平台佣金", color: "#12B76A", hint: "服务 / 结算" }, { key: "fulfillment", label: "履约物流", color: "#F79009", hint: "快递 / 配送" }, { key: "ad_spend", label: "广告投放", color: "#7F56D9", hint: "推广 / 直播" }, { key: "warehouse_packaging", label: "仓储包装", color: "#0B1836", hint: "包材 / 仓储" }, { key: "returns", label: "退款售后", color: "#F04438", hint: "退款 / 售后" }, { key: "labor", label: "人工工资", color: "#667085", hint: "运营 / 客服" }, { key: "other", label: "其他", color: "#A3AEC2", hint: "其他支出" }]), hiddenCost: [{ key: "refund", label: "退款退货潜在漏损", rate: .05, basisKeys: ["revenue"], tip: "按渠道、商品和原因拆分退款。" }, { key: "platform", label: "平台结算漏损", rate: .06, basisKeys: ["platform_fee"], tip: "逐单核对活动、佣金和到账金额。" }, { key: "ad", label: "广告无效消耗", rate: .12, basisKeys: ["ad_spend"], tip: "跟踪投产比与退款后收入。" }, { key: "inventory", label: "库存资金占用", rate: .015, basisKeys: ["goods_purchase"], tip: "按库龄和周转天数清理库存。" }] },
  beauty: { id: "beauty", label: "美业服务", descriptor: "美甲 / 美发 / 美容工作室", storeName: "美艺工作室", budget: 125000, entityLabel: "服务项目", formulaLabel: "服务耗用", unitLabel: "次", risk: "工时空置与爽约正在拉低利润", riskNote: "先看低峰时段的预约密度，再调整技师排班与到店提醒。", categories: categories([{ key: "materials", label: "产品耗材", color: "#1677FF", hint: "产品 / 耗材" }, { key: "technician_labor", label: "技师工资", color: "#12B76A", hint: "底薪 / 提成" }, { key: "rent_utilities", label: "房租水电", color: "#F79009", hint: "门店 / 工位" }, { key: "marketing", label: "营销推广", color: "#7F56D9", hint: "内容 / 获客" }, { key: "depreciation", label: "设备折旧", color: "#0B1836", hint: "仪器 / 设备" }, { key: "sundries", label: "耗品杂项", color: "#F04438", hint: "清洁 / 杂项" }, { key: "other", label: "其他", color: "#A3AEC2", hint: "其他支出" }]), hiddenCost: [{ key: "idle", label: "工时空置（基准估算）", rate: .4, basisKeys: ["technician_labor"], tip: "录入预约与可售工时后可校准。" }, { key: "noshow", label: "爽约损失（基准估算）", rate: .1, basisKeys: ["revenue"], tip: "到店前 24 小时确认预约。" }, { key: "chair", label: "空置工位", rate: .028, basisKeys: ["rent_utilities"], tip: "提高翻台或安排分时合租。" }] },
  stall: { id: "stall", label: "小商贩", descriptor: "夜市 / 集市 / 流动摊位", storeName: "晚风夜市摊", budget: 68000, entityLabel: "货品", formulaLabel: "进货构成", unitLabel: "件", risk: "尾货折价和摊位费占比偏高", riskNote: "按客流分批进货，日终前主动清尾，别把固定成本留到明天。", categories: categories([{ key: "purchase", label: "进货成本", color: "#1677FF", hint: "货品 / 补货" }, { key: "stall_fee", label: "摊位费", color: "#F79009", hint: "场地 / 市集" }, { key: "transport_handling", label: "交通搬运", color: "#12B76A", hint: "交通 / 搬运" }, { key: "clearance_loss", label: "损耗折价", color: "#F04438", hint: "尾货 / 损耗" }, { key: "misc", label: "其他杂费", color: "#A3AEC2", hint: "其他支出" }]), hiddenCost: [{ key: "loss", label: "货品损耗", rate: .07, basisKeys: ["purchase"], tip: "按客流分批进货，减少隔夜损耗。" }, { key: "fee", label: "摊位费占比", rate: .1, basisKeys: ["revenue"], tip: "仅作为未入账成本的参考。" }, { key: "gap", label: "出摊空档", rate: .15, basisKeys: ["stall_fee", "transport_handling"], tip: "为雨天和缺勤准备替代销售渠道。" }, { key: "clearance", label: "尾货折价", rate: .03, basisKeys: ["purchase"], tip: "预估当日客流，宁可少进勤补。" }] },
};

const amounts: Record<IndustryId, number[]> = { canteen: [61240, 28800, 15480, 10800, 4560, 3860, 3900], retail: [58820, 22800, 18400, 9120, 6240, 4680, 5400], ecommerce: [56620, 22960, 14280, 18640, 7320, 5620, 8200, 5000], beauty: [18420, 37800, 24600, 9180, 3620, 1680, 1120], stall: [27800, 8260, 6780, 4480, 3960] };
const sales: Record<IndustryId, number> = { canteen: 214300, retail: 235800, ecommerce: 214300, beauty: 198600, stall: 106400 };
const factors = [.82, .87, .91, .94, .97, 1];
const seedCards: Record<IndustryId, Omit<CostCard, "id" | "workspaceId" | "industryId">[]> = { canteen: [{ name: "水煮鱼", kind: "热菜", unit: "份", salePrice: 68, labor: 4.2, overhead: 1.8, status: "attention", history: [26.1, 25.8, 26.4, 25.9, 25.2, 24.6], items: [{ id: "b1", name: "黑鱼", spec: "750g", quantity: "1 条", amount: 12.9 }, { id: "b2", name: "黄豆芽", spec: "300g", quantity: "1 份", amount: 1.6 }, { id: "b3", name: "干辣椒 / 花椒", spec: "", quantity: "1 份", amount: 2.4 }, { id: "b4", name: "食用油及辅料", spec: "", quantity: "1 份", amount: 1.7 }] }], retail: [{ name: "云朵枕套", kind: "家居 SKU", unit: "件", salePrice: 59, labor: 2.6, overhead: 3.2, status: "healthy", history: [33, 31, 30, 30, 29, 28], items: [{ id: "r1", name: "进货价", spec: "单件", quantity: "1 件", amount: 20 }, { id: "r2", name: "入库物流", spec: "单件", quantity: "1 件", amount: 2.2 }] }], ecommerce: [{ name: "轻盈收纳盒", kind: "平台 SKU", unit: "件", salePrice: 68, labor: 3.2, overhead: 4.1, status: "healthy", history: [34, 33, 32, 31, 31, 30], items: [{ id: "e1", name: "货品采购", spec: "单件", quantity: "1 件", amount: 20 }, { id: "e2", name: "快递与包材", spec: "单件", quantity: "1 件", amount: 5.6 }, { id: "e3", name: "平台佣金", spec: "单件", quantity: "1 件", amount: 5.2 }] }], beauty: [{ name: "轻氧小气泡", kind: "护理项目", unit: "次", salePrice: 328, labor: 78, overhead: 36, status: "healthy", history: [176, 170, 174, 168, 165, 162], items: [{ id: "m1", name: "清洁套盒", spec: "单次", quantity: "1 套", amount: 32 }, { id: "m2", name: "修护精华", spec: "单次", quantity: "1 份", amount: 16 }] }], stall: [{ name: "夜市烤肠", kind: "摊位货品", unit: "份", salePrice: 12, labor: 1.2, overhead: .8, status: "healthy", history: [5.2, 5.1, 5.3, 5.4, 5.1, 5], items: [{ id: "s1", name: "香肠", spec: "单份", quantity: "1 根", amount: 2.4 }, { id: "s2", name: "调料与包装", spec: "单份", quantity: "1 份", amount: .6 }] }] };

function createCategories(industryId: IndustryId) { return industryTemplates[industryId].categories.map((category) => ({ ...category, id: `${industryId}-${category.key}`, workspaceId: WORKSPACE_ID, industryId })); }
function makeEntry(industryId: IndustryId, input: Omit<LedgerEntry, "id" | "workspaceId" | "industryId" | "templateVersion" | "createdAt" | "updatedAt">): LedgerEntry { const time = `${input.occurredAt}T12:00:00.000Z`; return { ...input, id: uid("seed"), workspaceId: WORKSPACE_ID, industryId, templateVersion: 2, createdAt: time, updatedAt: time }; }
function createSeedEntries(industryId: IndustryId) { const template = industryTemplates[industryId]; return periods.flatMap((period, periodIndex) => { const factor = factors[periodIndex]; const date = `${period}-14`; const sale = makeEntry(industryId, { occurredAt: date, eventType: "sale", ledgerRole: "revenue", cashDirection: "inflow", amountFen: toFen(Math.round(sales[industryId] * factor)), categoryKey: "sales", merchant: `${template.storeName}日结`, note: "演示销售日结", status: "posted", hasAttachment: true }); const expenses = template.categories.map((category, index) => makeEntry(industryId, { occurredAt: date, eventType: "expense", ledgerRole: category.ledgerRole === "cogs" ? "cogs" : "opex", cashDirection: "outflow", amountFen: toFen(Math.round((amounts[industryId][index] || 0) * factor)), categoryKey: category.key, merchant: `${category.label}结算`, note: category.hint, status: "posted", hasAttachment: index % 2 === 0 })); return [sale, ...expenses]; }); }
function createCards(industryId: IndustryId) { return seedCards[industryId].map((card, index) => ({ ...card, id: `${industryId}-card-${index + 1}`, workspaceId: WORKSPACE_ID, industryId })); }
function createSuppliers(industryId: IndustryId): Supplier[] { return industryTemplates[industryId].categories.slice(0, 4).map((category, index) => ({ id: `${industryId}-supplier-${index + 1}`, workspaceId: WORKSPACE_ID, industryIds: [industryId], name: `${category.label}${index === 0 ? "供应商" : "服务商"}`, contact: `联系人 ${index + 1}`, categoryKey: category.key, spend: Math.round((amounts[industryId][index] || 1000) * .65), orders: 3 + index * 4, trend: index % 2 === 0 ? "up" : "down" })); }
function createSkus(industryId: IndustryId): Sku[] { return createCards(industryId).map((card, index) => { const value = calcCard(card); return { id: `${industryId}-sku-${index + 1}`, workspaceId: WORKSPACE_ID, industryId, cardId: card.id, code: `${industryId.slice(0, 3).toUpperCase()}-${String(index + 1).padStart(3, "0")}`, name: card.name, unit: card.unit, unitPriceFen: toFen(card.salePrice), unitCostFen: toFen(value.cost), active: true }; }); }
function createSeedState(): BookState { const ids = Object.keys(industryTemplates) as IndustryId[]; return { schemaVersion: 3, workspace: { id: WORKSPACE_ID, activeIndustryId: "ecommerce", budgets: Object.fromEntries(ids.map((id) => [id, { amountFen: toFen(industryTemplates[id].budget), basis: "operating_cost" as BudgetBasis }])) as Record<IndustryId, Budget>, salesTargets: defaultSalesTargets(), healthSettings: defaultHealthSettings(), channelPricing: defaultChannelPricing(), switchedAt: "2026-07-14T10:00:00.000Z", dataMode: "demo" }, categories: ids.flatMap(createCategories), entries: ids.flatMap(createSeedEntries), cards: ids.flatMap(createCards), skus: ids.flatMap(createSkus), orders: [], refunds: [], suppliers: ids.flatMap(createSuppliers), salesTargetArchives: [], closedReports: [], switchLog: [] }; }

function migrateLegacy(legacy: any): BookState { const state = createSeedState(); const migratedEntries: LedgerEntry[] = (legacy.records || []).map((record: any) => { const eventType: LedgerEventType = record.type === "refund" ? "customer_refund" : record.type === "income" ? "income" : "expense"; const category = (legacy.categories || []).find((item: any) => item.key === record.categoryKey); const ledgerRole: LedgerRole = eventType === "income" ? "other_income" : eventType === "customer_refund" ? "revenue" : category?.ledgerRole || roleFor(record.categoryKey); const cashDirection: CashDirection = eventType === "income" ? "inflow" : "outflow"; return { id: record.id || uid("legacy"), workspaceId: record.workspaceId || WORKSPACE_ID, industryId: record.industryId, templateVersion: 1, occurredAt: record.date, eventType, ledgerRole, cashDirection, amountFen: toFen(Number(record.amount || 0)), categoryKey: record.categoryKey, merchant: record.merchant || "历史记录", note: record.note || "", status: record.status === "pending" ? "draft" : "posted", hasAttachment: Boolean(record.hasAttachment), createdAt: record.createdAt || now(), updatedAt: now() }; }); const budgets = Object.fromEntries((Object.keys(industryTemplates) as IndustryId[]).map((id) => [id, { amountFen: toFen(legacy.workspace?.budgetByIndustry?.[id] || industryTemplates[id].budget), basis: "operating_cost" as BudgetBasis }])) as Record<IndustryId, Budget>; return { ...state, workspace: { ...state.workspace, activeIndustryId: legacy.workspace?.activeIndustryId || "ecommerce", budgets, dataMode: "legacy_review" }, categories: legacy.categories?.map((category: any) => ({ ...category, ledgerRole: category.ledgerRole || roleFor(category.key) })) || state.categories, entries: migratedEntries, cards: legacy.cards || state.cards, suppliers: legacy.suppliers || state.suppliers, switchLog: legacy.switchLog || [] }; }
function migrateV2(legacy: any): BookState { const ids = Object.keys(industryTemplates) as IndustryId[]; return normalizeState({ ...legacy, schemaVersion: 3, skus: legacy.skus?.length ? legacy.skus : ids.flatMap(createSkus), orders: legacy.orders || [], refunds: legacy.refunds || [] }); }
function normalizeState(raw: any): BookState { const fallback = defaultChannelPricing(); const channelPricing = { ...fallback, ...(raw.workspace?.channelPricing || {}) }; const salesTargets = { ...defaultSalesTargets(), ...(raw.workspace?.salesTargets || {}) }; const healthDefaults = defaultHealthSettings(); const healthSettings = Object.fromEntries((Object.keys(industryTemplates) as IndustryId[]).map((id) => [id, { ...healthDefaults[id], ...(raw.workspace?.healthSettings?.[id] || {}) }])) as Record<IndustryId, HealthSettings>; const orders = (raw.orders || []).map((order: any) => ({ ...order, pricing: { ...(channelPricing[order.channel as OrderChannel] || fallback.other), ...(order.pricing || {}) } })); return { ...raw, workspace: { ...raw.workspace, salesTargets, healthSettings, channelPricing }, salesTargetArchives: raw.salesTargetArchives || [], orders } as BookState; }
function loadState(): BookState { if (typeof window === "undefined") return createSeedState(); try { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) return normalizeState(JSON.parse(saved)); const v2 = window.localStorage.getItem(V2_STORAGE_KEY); if (v2) { const backupKey = `${V2_STORAGE_KEY}-backup-${Date.now()}`; window.localStorage.setItem(backupKey, v2); const migrated = migrateV2(JSON.parse(v2)); window.localStorage.setItem(STORAGE_KEY, JSON.stringify(migrated)); return migrated; } const legacy = window.localStorage.getItem(LEGACY_STORAGE_KEY); if (legacy) { const backupKey = `${LEGACY_STORAGE_KEY}-backup-${Date.now()}`; window.localStorage.setItem(backupKey, legacy); const migrated = migrateLegacy(JSON.parse(legacy)); window.localStorage.setItem(STORAGE_KEY, JSON.stringify(migrated)); return migrated; } } catch { /* 保持种子账本可用 */ } return createSeedState(); }

export function calcCard(card: CostCard) { const material = Number(card.items.reduce((sum, item) => sum + Number(item.amount || 0), 0).toFixed(2)); const cost = Number((material + card.labor + card.overhead).toFixed(2)); const marginRate = card.salePrice ? Number(((card.salePrice - cost) / card.salePrice * 100).toFixed(1)) : 0; return { material, cost, marginRate }; }
const cardStatusFor = (card: CostCard): CostCard["status"] => { const marginRate = calcCard(card).marginRate; return marginRate < 25 ? "risk" : marginRate < 45 ? "attention" : "healthy"; };
function skuFromCard(card: CostCard, existing?: Sku): Sku { const cost = calcCard(card).cost; return { id: existing?.id || uid("sku"), workspaceId: WORKSPACE_ID, industryId: card.industryId, cardId: card.id, code: existing?.code || `${card.industryId.slice(0, 3).toUpperCase()}-${card.id.slice(-4).toUpperCase()}`, name: card.name, unit: card.unit, unitPriceFen: toFen(card.salePrice), unitCostFen: toFen(cost), active: true }; }
const dateLabel = (date: string) => date === "2026-07-14" ? "今天" : date === "2026-07-13" ? "昨天" : date.slice(5).replace("-", " 月 ") + " 日";
const asRecord = (entry: LedgerEntry): CostRecord => ({ ...entry, date: entry.occurredAt, type: entry.eventType === "customer_refund" ? "refund" : entry.eventType === "sale" || entry.eventType === "income" ? "income" : "expense", amount: fromFen(entry.amountFen), status: entry.status === "draft" ? "pending" : "accounted" });

export function useCostBook() {
  const [state, setState] = useState<BookState>(loadState);
  useEffect(() => { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [state]);
  const activeIndustryId = state.workspace.activeIndustryId; const template = industryTemplates[activeIndustryId]; const currentPeriod = "2026-07";
  const categories = useMemo(() => state.categories.filter((item) => item.industryId === activeIndustryId && !item.archived), [state.categories, activeIndustryId]);
  const activeEntries = useMemo(() => state.entries.filter((item) => item.industryId === activeIndustryId).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt) || b.createdAt.localeCompare(a.createdAt)), [state.entries, activeIndustryId]);
  const records = useMemo(() => activeEntries.map(asRecord), [activeEntries]); const cards = useMemo(() => state.cards.filter((item) => item.industryId === activeIndustryId), [state.cards, activeIndustryId]); const skus = useMemo(() => state.skus.filter((item) => item.industryId === activeIndustryId && item.active), [state.skus, activeIndustryId]); const orders = useMemo(() => state.orders.filter((item) => item.industryId === activeIndustryId).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt) || b.createdAt.localeCompare(a.createdAt)), [state.orders, activeIndustryId]); const refunds = useMemo(() => state.refunds.filter((item) => item.industryId === activeIndustryId).sort((a, b) => b.occurredAt.localeCompare(a.occurredAt) || b.createdAt.localeCompare(a.createdAt)), [state.refunds, activeIndustryId]); const suppliers = useMemo(() => state.suppliers.filter((item) => item.industryIds.includes(activeIndustryId) || item.industryIds.includes("shared")), [state.suppliers, activeIndustryId]);
  const budget = state.workspace.budgets[activeIndustryId]; const salesTarget = fromFen(state.workspace.salesTargets[activeIndustryId] || 0); const healthSettings = state.workspace.healthSettings[activeIndustryId]; const salesTargetArchives = useMemo(() => state.salesTargetArchives.filter((item) => item.industryId === activeIndustryId).sort((a, b) => b.period.localeCompare(a.period)), [activeIndustryId, state.salesTargetArchives]); const currentEntries = useMemo(() => entriesForPeriod(state.entries, activeIndustryId, currentPeriod), [state.entries, activeIndustryId]); const metrics = useMemo(() => buildMetrics(currentEntries, budget), [currentEntries, budget]);
  const categoryTotals = useMemo(() => categories.map((category) => ({ ...category, amount: fromFen(currentEntries.filter((entry) => entry.categoryKey === category.key && (entry.ledgerRole === "cogs" || entry.ledgerRole === "opex")).reduce((sum, entry) => sum + entry.amountFen, 0)) })).sort((a, b) => b.amount - a.amount), [categories, currentEntries]);
  const totals = useMemo(() => ({ totalCost: fromFen(metrics.cogsFen + metrics.operatingExpenseFen), revenue: fromFen(metrics.netRevenueFen), grossSales: fromFen(metrics.grossSalesFen), refunds: fromFen(metrics.refundsFen), cogs: fromFen(metrics.cogsFen), operatingExpense: fromFen(metrics.operatingExpenseFen), grossProfit: fromFen(metrics.grossProfitFen), operatingProfit: fromFen(metrics.operatingProfitFen), marginRate: metrics.grossMarginRate, grossMarginRate: metrics.grossMarginRate, operatingMarginRate: metrics.operatingMarginRate, budget: fromFen(budget.amountFen), budgetUsed: metrics.budgetUsedRate, budgetRemaining: fromFen(metrics.budgetRemainingFen), categoryTotals }), [metrics, budget, categoryTotals]);
  const trend = useMemo(() => periodSeries(state.entries, activeIndustryId, currentPeriod, 6, budget).map(({ period, metrics: item }) => ({ month: period, cost: fromFen(item.cogsFen + item.operatingExpenseFen), revenue: fromFen(item.netRevenueFen), marginRate: item.grossMarginRate, operatingMarginRate: item.operatingMarginRate })), [state.entries, activeIndustryId, budget]);
  const reports = useMemo(() => periods.slice(-3).reverse().map((month) => { const reportEntries = entriesForPeriod(state.entries, activeIndustryId, month); const reportMetrics = buildMetrics(reportEntries, budget); const snapshot = categories.map((category) => { const amount = fromFen(reportEntries.filter((entry) => entry.categoryKey === category.key && (entry.ledgerRole === "cogs" || entry.ledgerRole === "opex")).reduce((sum, entry) => sum + entry.amountFen, 0)); const total = fromFen(reportMetrics.cogsFen + reportMetrics.operatingExpenseFen); return { key: category.key, label: category.label, amount, pct: total ? Number((amount / total * 100).toFixed(1)) : 0, delta: 0 }; }); const closed = state.closedReports.find((item) => item.industryId === activeIndustryId && item.month === month); return closed || { id: `${activeIndustryId}-${month}-draft`, workspaceId: WORKSPACE_ID, industryId: activeIndustryId, month, revenue: fromFen(reportMetrics.netRevenueFen), cost: fromFen(reportMetrics.cogsFen + reportMetrics.operatingExpenseFen), margin: fromFen(reportMetrics.grossProfitFen), grossMarginRate: reportMetrics.grossMarginRate, operatingMarginRate: reportMetrics.operatingMarginRate, status: "draft" as const, snapshot }; }), [state.entries, activeIndustryId, budget, categories, state.closedReports]);
  const closeReport = (month: string) => setState((current) => { if (current.closedReports.some((report) => report.industryId === current.workspace.activeIndustryId && report.month === month)) return current; const industryId = current.workspace.activeIndustryId; const reportEntries = entriesForPeriod(current.entries, industryId, month); const reportBudget = current.workspace.budgets[industryId]; const reportMetrics = buildMetrics(reportEntries, reportBudget); const reportCategories = current.categories.filter((category) => category.industryId === industryId && !category.archived); const totalCost = fromFen(reportMetrics.cogsFen + reportMetrics.operatingExpenseFen); const snapshot = reportCategories.map((category) => { const amount = fromFen(reportEntries.filter((entry) => entry.categoryKey === category.key && (entry.ledgerRole === "cogs" || entry.ledgerRole === "opex")).reduce((sum, entry) => sum + entry.amountFen, 0)); return { key: category.key, label: category.label, amount, pct: totalCost ? Number((amount / totalCost * 100).toFixed(1)) : 0, delta: 0 }; }); const report: Report = { id: uid("report"), workspaceId: WORKSPACE_ID, industryId, month, revenue: fromFen(reportMetrics.netRevenueFen), cost: totalCost, margin: fromFen(reportMetrics.grossProfitFen), grossMarginRate: reportMetrics.grossMarginRate, operatingMarginRate: reportMetrics.operatingMarginRate, status: "closed", snapshot }; return { ...current, closedReports: [report, ...current.closedReports] }; });
  const hiddenCosts = useMemo(() => template.hiddenCost.map((rule) => { const base = rule.basisKeys.reduce((sum, key) => sum + (key === "revenue" ? totals.revenue : totals.categoryTotals.find((category) => category.key === key)?.amount || 0), 0); const estimate = Math.round(base * rule.rate); const health = estimate / Math.max(totals.revenue, 1) < .04 ? 85 : estimate / Math.max(totals.revenue, 1) < .08 ? 72 : 54; return { ...rule, base, estimate, health, source: "benchmark" as const }; }), [template.hiddenCost, totals.categoryTotals, totals.revenue]);
  const getPeriodView = (period: string) => { const entries = entriesForPeriod(state.entries, activeIndustryId, period); const periodMetrics = buildMetrics(entries, budget); const periodCategories = categories.map((category) => ({ ...category, amount: fromFen(entries.filter((entry) => entry.categoryKey === category.key && (entry.ledgerRole === "cogs" || entry.ledgerRole === "opex")).reduce((sum, entry) => sum + entry.amountFen, 0)) })).sort((a, b) => b.amount - a.amount); return { period, metrics: periodMetrics, totals: { totalCost: fromFen(periodMetrics.cogsFen + periodMetrics.operatingExpenseFen), revenue: fromFen(periodMetrics.netRevenueFen), grossProfit: fromFen(periodMetrics.grossProfitFen), operatingProfit: fromFen(periodMetrics.operatingProfitFen), grossMarginRate: periodMetrics.grossMarginRate, operatingMarginRate: periodMetrics.operatingMarginRate, budgetUsed: periodMetrics.budgetUsedRate, categoryTotals: periodCategories } }; };
  const skuMetrics = useMemo(() => skus.map((sku) => { const soldLines = orders.flatMap((order) => order.lines.filter((line) => line.skuId === sku.id)); const skuRefunds = refunds.filter((refund) => refund.skuId === sku.id); const soldQuantity = soldLines.reduce((sum, line) => sum + line.quantity, 0); const refundedQuantity = skuRefunds.reduce((sum, refund) => sum + refund.quantity, 0); const revenueFen = soldLines.reduce((sum, line) => sum + lineRevenueFen(line), 0); const refundFen = skuRefunds.reduce((sum, refund) => sum + refund.refundFen, 0); const cogsFen = soldLines.reduce((sum, line) => sum + lineCogsFen(line), 0); const recoveredCostFen = skuRefunds.reduce((sum, refund) => sum + refund.recoveredCostFen, 0); const netRevenueFen = revenueFen - refundFen; const netCogsFen = cogsFen - recoveredCostFen; return { ...sku, soldQuantity, refundedQuantity, netRevenue: fromFen(netRevenueFen), refunds: fromFen(refundFen), cogs: fromFen(netCogsFen), grossProfit: fromFen(netRevenueFen - netCogsFen), grossMarginRate: netRevenueFen > 0 ? Number(((netRevenueFen - netCogsFen) / netRevenueFen * 100).toFixed(1)) : 0 }; }).sort((a, b) => b.netRevenue - a.netRevenue), [skus, orders, refunds]);
  const channelTemplates = state.workspace.channelPricing;
  const orderWarnings = useMemo(() => orders.flatMap((order) => { const warning = getOrderPricingAlert(order); return warning ? [warning] : []; }), [orders]);
  const switchIndustry = (targetIndustryId: IndustryId) => { if (targetIndustryId !== activeIndustryId) setState((current) => ({ ...current, workspace: { ...current.workspace, activeIndustryId: targetIndustryId, switchedAt: now() }, switchLog: [{ id: uid("switch"), from: current.workspace.activeIndustryId, to: targetIndustryId, at: now(), strategy: "future_only" }, ...current.switchLog] })); };
  const addOrder = (input: { orderNo?: string; channel: OrderChannel; buyer: string; date: string; lines: { skuId: string; quantity: number }[] }) => setState((current) => { const validLines = input.lines.filter((line) => line.quantity > 0).map((line) => { const sku = current.skus.find((item) => item.id === line.skuId && item.industryId === current.workspace.activeIndustryId); if (!sku) throw new Error("SKU 不存在或不属于当前行业"); return { id: uid("line"), skuId: sku.id, skuCode: sku.code, skuName: sku.name, unit: sku.unit, quantity: line.quantity, refundedQuantity: 0, unitPriceFen: sku.unitPriceFen, unitCostFen: sku.unitCostFen } as OrderLine; }); if (!validLines.length) return current; const order: Order = { id: uid("order"), workspaceId: WORKSPACE_ID, industryId: current.workspace.activeIndustryId, orderNo: input.orderNo?.trim() || `ORD-${Date.now().toString().slice(-6)}`, channel: input.channel, buyer: input.buyer.trim() || "散客", occurredAt: input.date, status: "paid", lines: validLines, pricing: { ...current.workspace.channelPricing[input.channel] }, saleEntryId: uid("sale"), createdAt: now(), updatedAt: now() }; const cogsCategoryKey = current.categories.find((category) => category.industryId === order.industryId && category.ledgerRole === "cogs")?.key || "goods_purchase"; return { ...current, workspace: { ...current.workspace, dataMode: "live" }, orders: [order, ...current.orders], entries: [...buildOrderEntries({ order, cogsCategoryKey, now: now() }), ...current.entries] }; });
  const createRefund = (input: { orderId: string; lineId: string; quantity: number; refundAmount: number; refundFee: number; reason: RefundReason; recoveryStatus: ReturnRecoveryStatus; date: string }) => { const order = state.orders.find((item) => item.id === input.orderId && item.industryId === activeIndustryId); const line = order?.lines.find((item) => item.id === input.lineId); if (!order || !line) return { ok: false, reason: "订单或 SKU 明细不存在" }; if (input.quantity <= 0 || input.quantity > refundableQuantity(line)) return { ok: false, reason: "退款数量超过可退数量" }; if (input.refundAmount <= 0) return { ok: false, reason: "请填写正确的退款金额" }; setState((current) => { const targetOrder = current.orders.find((item) => item.id === input.orderId)!; const targetLine = targetOrder.lines.find((item) => item.id === input.lineId)!; const refund: RefundCase = { id: uid("refund"), workspaceId: WORKSPACE_ID, industryId: current.workspace.activeIndustryId, orderId: targetOrder.id, orderLineId: targetLine.id, skuId: targetLine.skuId, quantity: input.quantity, refundFen: toFen(input.refundAmount), refundFeeFen: toFen(input.refundFee || 0), reason: input.reason, recoveryStatus: input.recoveryStatus, recoveredCostFen: input.recoveryStatus === "sellable_restocked" ? targetLine.unitCostFen * input.quantity : 0, occurredAt: input.date, refundEntryId: uid("refund-entry"), createdAt: now() }; const entries = buildRefundEntries({ refund, order: targetOrder, line: targetLine, now: now() }); const orders = current.orders.map((candidate) => candidate.id !== targetOrder.id ? candidate : { ...candidate, status: targetLine.refundedQuantity + input.quantity === targetLine.quantity ? "refunded" as const : "partially_refunded" as const, lines: candidate.lines.map((candidateLine) => candidateLine.id !== targetLine.id ? candidateLine : { ...candidateLine, refundedQuantity: candidateLine.refundedQuantity + input.quantity }), updatedAt: now() }); return { ...current, workspace: { ...current.workspace, dataMode: "live" }, orders, refunds: [refund, ...current.refunds], entries: [...entries, ...current.entries] }; }); return { ok: true }; };
  const updateSkuCost = (skuId: string, unitCost: number) => { if (unitCost < 0) return { ok: false, reason: "商品成本不能为负数" }; setState((current) => ({ ...current, skus: current.skus.map((sku) => sku.id === skuId && sku.industryId === current.workspace.activeIndustryId ? { ...sku, unitCostFen: toFen(unitCost) } : sku) })); return { ok: true }; };
  const updateChannelPricing = (channel: OrderChannel, input: Partial<ChannelPricingSnapshot>) => setState((current) => ({ ...current, workspace: { ...current.workspace, channelPricing: { ...current.workspace.channelPricing, [channel]: { ...current.workspace.channelPricing[channel], ...input, commissionRatePct: Math.max(0, Number(input.commissionRatePct ?? current.workspace.channelPricing[channel].commissionRatePct)), fulfillmentCost: Math.max(0, Number(input.fulfillmentCost ?? current.workspace.channelPricing[channel].fulfillmentCost)), targetContributionMarginPct: Math.max(0, Number(input.targetContributionMarginPct ?? current.workspace.channelPricing[channel].targetContributionMarginPct)), roundingStep: Math.max(0.01, Number(input.roundingStep ?? current.workspace.channelPricing[channel].roundingStep)) } } } }));
  const addRecord = (input: { categoryKey: string; date: string; type: RecordType; amount: number; merchant: string; note: string; status: RecordStatus; hasAttachment: boolean; supplierId?: string; refundFee?: number; recovery?: number }) => { setState((current) => { const category = current.categories.find((item) => item.industryId === current.workspace.activeIndustryId && item.key === input.categoryKey); const isRefund = input.type === "refund"; const entry: LedgerEntry = { id: uid("record"), workspaceId: WORKSPACE_ID, industryId: current.workspace.activeIndustryId, templateVersion: 3, occurredAt: input.date, eventType: isRefund ? "customer_refund" : input.type === "income" ? "sale" : "expense", ledgerRole: isRefund ? "revenue" : input.type === "income" ? "revenue" : category?.ledgerRole === "cogs" ? "cogs" : "opex", cashDirection: input.type === "income" ? "inflow" : "outflow", amountFen: toFen(input.amount), categoryKey: input.categoryKey, merchant: input.merchant, note: input.note, status: input.status === "pending" ? "draft" : "posted", hasAttachment: input.hasAttachment, supplierId: input.supplierId, createdAt: now(), updatedAt: now() }; const extras: LedgerEntry[] = []; if (isRefund && input.refundFee && input.refundFee > 0) extras.push({ ...entry, id: uid("refund-fee"), relatedEntryId: entry.id, eventType: "expense", ledgerRole: "opex", amountFen: toFen(input.refundFee), categoryKey: "returns", note: `${input.note} · 退款手续费`, createdAt: now(), updatedAt: now() }); if (isRefund && input.recovery && input.recovery > 0) extras.push({ ...entry, id: uid("recovery"), relatedEntryId: entry.id, eventType: "inventory_return", ledgerRole: "cogs", cashDirection: "none", amountFen: -toFen(input.recovery), categoryKey: "returns", note: `${input.note} · 退货回收成本`, createdAt: now(), updatedAt: now() }); return { ...current, entries: [entry, ...extras, ...current.entries] }; }); };
  const updateRecord = (id: string, input: Partial<{ categoryKey: string; date: string; type: RecordType; amount: number; merchant: string; note: string; status: RecordStatus; hasAttachment: boolean; supplierId: string }>) => setState((current) => ({ ...current, entries: current.entries.map((entry) => { if (entry.id !== id) return entry; const nextType = input.type ?? (entry.eventType === "customer_refund" ? "refund" : entry.eventType === "sale" || entry.eventType === "income" ? "income" : "expense"); const categoryKey = input.categoryKey ?? entry.categoryKey; const category = current.categories.find((item) => item.industryId === entry.industryId && item.key === categoryKey); const isRefund = nextType === "refund"; return { ...entry, occurredAt: input.date ?? entry.occurredAt, amountFen: input.amount === undefined ? entry.amountFen : toFen(input.amount), categoryKey, eventType: isRefund ? "customer_refund" : nextType === "income" ? "sale" : "expense", ledgerRole: isRefund || nextType === "income" ? "revenue" : category?.ledgerRole === "cogs" ? "cogs" : "opex", cashDirection: nextType === "income" ? "inflow" : "outflow", status: input.status === "pending" ? "draft" : "posted", merchant: input.merchant ?? entry.merchant, note: input.note ?? entry.note, supplierId: input.supplierId ?? entry.supplierId, hasAttachment: input.hasAttachment ?? entry.hasAttachment, updatedAt: now() }; }) }));
  const removeRecord = (id: string) => setState((current) => ({ ...current, entries: current.entries.filter((entry) => entry.id !== id && entry.relatedEntryId !== id) }));
  const addCard = (input: { name: string; kind: string; unit: string; salePrice: number; labor: number; overhead: number; items: Omit<BomItem, "id">[] }) => setState((current) => { const unit = input.unit.trim() || template.unitLabel; const cardBase: CostCard = { id: uid("card"), workspaceId: WORKSPACE_ID, industryId: current.workspace.activeIndustryId, name: input.name.trim(), kind: input.kind.trim() || `${template.entityLabel} SKU`, unit, salePrice: input.salePrice, labor: input.labor, overhead: input.overhead, items: input.items.map((item) => ({ ...item, id: uid("bom"), name: item.name.trim() || "直接材料", quantity: item.quantity.trim() || `1 ${unit}` })), history: [], status: "healthy" }; const card = { ...cardBase, history: [calcCard(cardBase).cost], status: cardStatusFor(cardBase) }; return { ...current, workspace: { ...current.workspace, dataMode: "live" }, cards: [...current.cards, card], skus: [...current.skus, skuFromCard(card)] }; });
  const updateCard = (cardId: string, input: Partial<Pick<CostCard, "name" | "kind" | "unit" | "salePrice" | "labor" | "overhead">> & { items?: Omit<BomItem, "id">[] }) => setState((current) => { let updatedCard: CostCard | null = null; const cards = current.cards.map((card) => { if (card.id !== cardId) return card; const { items: nextItems, ...base } = input; const items = nextItems ? nextItems.map((item, index) => ({ ...item, id: card.items[index]?.id || uid("bom"), name: item.name.trim() || "直接材料", quantity: item.quantity.trim() || `1 ${base.unit || card.unit}` })) : card.items; const draft: CostCard = { ...card, ...base, items }; const next: CostCard = { ...draft, history: [...draft.history.slice(-5), calcCard(draft).cost], status: cardStatusFor(draft) }; updatedCard = next; return next; }); return updatedCard ? { ...current, cards, skus: current.skus.map((sku) => sku.cardId === cardId ? skuFromCard(updatedCard!, sku) : sku) } : current; });
  const addBomItem = (cardId: string, item: Omit<BomItem, "id">) => setState((current) => { let updatedCard: CostCard | null = null; const cards = current.cards.map((card) => { if (card.id !== cardId) return card; const items = [...card.items, { ...item, id: uid("bom") }]; const draft = { ...card, items }; const next = { ...draft, history: [...card.history.slice(-5), calcCard(draft).cost], status: cardStatusFor(draft) }; updatedCard = next; return next; }); return updatedCard ? { ...current, cards, skus: current.skus.map((sku) => sku.cardId === cardId ? skuFromCard(updatedCard!, sku) : sku) } : current; });
  const updateBomItem = (cardId: string, itemId: string, input: Omit<BomItem, "id">) => setState((current) => { let updatedCard: CostCard | null = null; const cards = current.cards.map((card) => { if (card.id !== cardId) return card; const items = card.items.map((item) => item.id === itemId ? { ...input, id: itemId } : item); const draft = { ...card, items }; const next = { ...draft, history: [...card.history.slice(-5), calcCard(draft).cost], status: cardStatusFor(draft) }; updatedCard = next; return next; }); return updatedCard ? { ...current, cards, skus: current.skus.map((sku) => sku.cardId === cardId ? skuFromCard(updatedCard!, sku) : sku) } : current; });
  const removeBomItem = (cardId: string, itemId: string) => setState((current) => { let updatedCard: CostCard | null = null; const cards = current.cards.map((card) => { if (card.id !== cardId) return card; const items = card.items.filter((item) => item.id !== itemId); const draft = { ...card, items }; const next = { ...draft, history: [...card.history.slice(-5), calcCard(draft).cost], status: cardStatusFor(draft) }; updatedCard = next; return next; }); return updatedCard ? { ...current, cards, skus: current.skus.map((sku) => sku.cardId === cardId ? skuFromCard(updatedCard!, sku) : sku) } : current; });
  const removeCard = (cardId: string) => { const linkedSkuIds = state.skus.filter((sku) => sku.cardId === cardId).map((sku) => sku.id); if (state.orders.some((order) => order.lines.some((line) => linkedSkuIds.includes(line.skuId)))) return { ok: false, reason: "该成本卡已有订单成本快照，不能删除；可编辑为停售或保留归档。" }; setState((current) => ({ ...current, cards: current.cards.filter((card) => card.id !== cardId), skus: current.skus.filter((sku) => sku.cardId !== cardId) })); return { ok: true }; };
  const addSupplier = (input: Omit<Supplier, "id" | "workspaceId" | "industryIds" | "spend" | "orders" | "trend">) => setState((current) => ({ ...current, suppliers: [...current.suppliers, { ...input, id: uid("supplier"), workspaceId: WORKSPACE_ID, industryIds: [current.workspace.activeIndustryId], spend: 0, orders: 0, trend: "up" }] }));
  const removeSupplier = (id: string) => setState((current) => ({ ...current, suppliers: current.suppliers.filter((supplier) => supplier.id !== id) }));
  const addCategory = (input: Omit<Category, "id" | "workspaceId" | "industryId" | "ledgerRole"> & { ledgerRole?: Category["ledgerRole"] }) => setState((current) => ({ ...current, categories: [...current.categories, { ...input, ledgerRole: input.ledgerRole || "opex", id: uid("category"), workspaceId: WORKSPACE_ID, industryId: current.workspace.activeIndustryId }] }));
  const removeCategory = (id: string) => { const category = state.categories.find((item) => item.id === id); if (!category) return { ok: false, reason: "分类不存在" }; if (state.entries.some((entry) => entry.industryId === activeIndustryId && entry.categoryKey === category.key)) return { ok: false, reason: "该分类下仍有关联流水，无法删除" }; setState((current) => ({ ...current, categories: current.categories.filter((item) => item.id !== id) })); return { ok: true }; };
  const updateBudget = (budgetAmount: number, basis: BudgetBasis = "operating_cost") => setState((current) => ({ ...current, workspace: { ...current.workspace, budgets: { ...current.workspace.budgets, [current.workspace.activeIndustryId]: { amountFen: toFen(budgetAmount), basis } } } }));
  const saveSalesTargetArchive = (period: string, targetAmount: number) => setState((current) => { const targetFen = toFen(Math.max(0, Number.isFinite(targetAmount) ? targetAmount : 0)); const industryId = current.workspace.activeIndustryId; const archive = { id: `${industryId}-${period}`, workspaceId: WORKSPACE_ID, industryId, period, targetFen, savedAt: now() }; const archives = [archive, ...current.salesTargetArchives.filter((item) => !(item.industryId === industryId && item.period === period))]; return { ...current, workspace: { ...current.workspace, salesTargets: period === currentPeriod ? { ...current.workspace.salesTargets, [industryId]: targetFen } : current.workspace.salesTargets }, salesTargetArchives: archives }; });
  const updateSalesTarget = (targetAmount: number) => saveSalesTargetArchive(currentPeriod, targetAmount);
  const updateHealthSettings = (input: Partial<HealthSettings>) => setState((current) => { const industryId = current.workspace.activeIndustryId; const previous = current.workspace.healthSettings[industryId]; return { ...current, workspace: { ...current.workspace, healthSettings: { ...current.workspace.healthSettings, [industryId]: { targetOperatingMarginPct: Math.max(0, Number(input.targetOperatingMarginPct ?? previous.targetOperatingMarginPct)), refundTolerancePct: Math.max(0, Number(input.refundTolerancePct ?? previous.refundTolerancePct)) } } } }; });
  return { state, activeIndustryId, template, categories, records, cards, skus, skuMetrics, orders, refunds, suppliers, reports, totals, trend, hiddenCosts, currentPeriod, getPeriodView, previousPeriod, dateLabel, channelTemplates, orderWarnings, salesTarget, salesTargetArchives, healthSettings, switchIndustry, addOrder, createRefund, updateSkuCost, updateChannelPricing, addRecord, updateRecord, removeRecord, closeReport, addCard, updateCard, removeCard, addBomItem, updateBomItem, removeBomItem, addSupplier, removeSupplier, addCategory, removeCategory, updateBudget, updateSalesTarget, saveSalesTargetArchive, updateHealthSettings };
}
